### ISSUE TITLE
Ideas for Final Project

### ISSUE THREAD

**Issue by Nutbarz** [Nutbarz/SystemsAnalysisGroup2#1]
Think of ideas for final project.

**Comment by Nutbarz** [comment]
upload custom recipes

**Comment by Nutbarz** [comment]
appliances available

**Comment by Max-Husky** [comment]
kitchen utensils needed/available

**Comment by ZachDallum** [comment]
allergy restrictions

**Comment by Max-Husky** [comment]
possible substitutions

**Comment by ZachDallum** [comment]
recipes based of ingredients on hand

**Comment by Nutbarz** [comment]
ingredients needed based on what you want to eat

**Comment by Nutbarz** [comment]
editing recipes based on user preference

**Comment by Nutbarz** [comment]
comments on how recipe turned out with review

**Comment by Nutbarz** [comment]
sourcing ingredients from stores
based on availability

**Comment by Nutbarz** [comment]
preferred stores

**Comment by Nutbarz** [comment]
references to buy appliances/utensils

**Comment by Nutbarz** [comment]
referencing cookbooks

**Comment by Nutbarz** [comment]
metadata scraper

**Comment by Nutbarz** [comment]
recipe suggestions
trending recipes
random recipes
daily recipes

**Comment by Nutbarz** [comment]
main screen recommendations
