### ISSUE TITLE
Benefits

### ISSUE THREAD

**Issue by Nutbarz** [Nutbarz/SystemsAnalysisGroup2#3]

**Comment by ZachDallum** [comment]
Easier weekly meal planning, allows user to search by what is important to them, gives user a weekly meal overview and creates them a shopping list with all the items needed.

**Comment by ZachDallum** [comment]
Allows user to follow dietary restrictions and watch out for their allergies

**Comment by Nutbarz** [comment]
product and store sponsorships for revenue
Ads

**Comment by Nutbarz** [comment]
membership or paying for app
